CREATE PROC FI_SP_ConsBeneficiarios
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT NOME, CPF, ID FROM CLIENTES WITH(NOLOCK)
	ELSE
		SELECT NOME, CPF, ID FROM CLIENTES WITH(NOLOCK) WHERE ID = @ID
END